"""migration

Revision ID: 02b8683004c8
Revises:
Create Date: 2025-11-26 11:49:08.705848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = '02b8683004c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###

    op.create_table(
        'gasoduto_transporte',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('objectid', sa.Integer(), nullable=True),
        sa.Column('id_duto', sa.Integer(), nullable=True),
        sa.Column('nome_dut_1', sa.String(length=254), nullable=True),
        sa.Column('label', sa.String(length=50), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('munic_orig', sa.String(length=254), nullable=True),
        sa.Column('munic_dest', sa.String(length=254), nullable=True),
        sa.Column('comprim_km', sa.Float(), nullable=True),
        sa.Column('shape_stle', sa.Float(), nullable=True),
        sa.Column('diam_pol_x', sa.String(length=50), nullable=True),
        sa.Column('p_max_op', sa.String(length=254), nullable=True),
        sa.Column('transporta', sa.String(length=50), nullable=True),
        sa.Column('fontes', sa.String(length=254), nullable=True),
        sa.Column('fontedata', sa.String(length=50), nullable=True),
        sa.Column('Inic Opera', sa.Integer(), nullable=True),
        sa.Column('categoria', sa.Integer(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('created_da', sa.Date(), nullable=True),
        sa.Column('last_edi_1', sa.Date(), nullable=True),
        sa.Column('created_us', sa.String(length=254), nullable=True),
        sa.Column('last_edite', sa.String(length=254), nullable=True),
        sa.Column('situacao', sa.String(length=254), nullable=True),
        sa.Column('geometry', Geometry(geometry_type='LINESTRINGZ', srid=4674), nullable=True),
    )

    # Cria índice espacial se ainda não existir
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relname = 'idx_gasoduto_transporte_geometry'
            ) THEN
                CREATE INDEX idx_gasoduto_transporte_geometry
                ON gasoduto_transporte
                USING gist(geometry);
            END IF;
        END $$;
    """)

    op.create_index(op.f('ix_gasoduto_transporte_id'), 'gasoduto_transporte', ['id'], unique=False)

    # IMPORTANT: Removed wrong Alembic autogen instruction
    # ### end commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(op.f('ix_gasoduto_transporte_id'), table_name='gasoduto_transporte')
    op.execute("DROP INDEX IF EXISTS idx_gasoduto_transporte_geometry;")
    op.drop_table('gasoduto_transporte')

    # Não recriar spatial_ref_sys (PostGIS cria automaticamente)
