"""initial

Revision ID: 13660b71bf4e
Revises: 
Create Date: 2025-12-04 14:10:20.199501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13660b71bf4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aterros_sanitarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('operador', sa.String(length=150), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('volume_recebido_toneladas_dia', sa.Float(), nullable=True),
    sa.Column('porte', sa.String(length=50), nullable=True),
    sa.Column('data_abertura', sa.String(), nullable=True),
    sa.Column('fonte_1', sa.String(length=500), nullable=True),
    sa.Column('fonte_2', sa.String(length=500), nullable=True),
    sa.Column('fonte_3', sa.String(length=500), nullable=True),
    sa.Column('m3_biomethane_per_ton_rsu', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aterros_sanitarios_id'), 'aterros_sanitarios', ['id'], unique=False)
    op.create_table('biometano_dados_abertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_ano', sa.String(length=20), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('regiao', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=True),
    sa.Column('capacidade_autorizada_de_producao_de_biometano_m_d', sa.Float(), nullable=True),
    sa.Column('capacidade_processamento_de_biogas_m_d', sa.Float(), nullable=True),
    sa.Column('volume_processado_de_biogas_m_d', sa.Float(), nullable=True),
    sa.Column('volume_processado_capacidade', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometano_dados_abertos_id'), 'biometano_dados_abertos', ['id'], unique=False)
    op.create_table('cap_num_usinas_acumuladas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_ano', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('capac_prd_m3dia', sa.Float(), nullable=True),
    sa.Column('qtdade_usinas', sa.Integer(), nullable=True),
    sa.Column('capac_prd_m3dia_acumulada', sa.Float(), nullable=True),
    sa.Column('qtdade_usinas_acumuladas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cap_num_usinas_acumuladas_id'), 'cap_num_usinas_acumuladas', ['id'], unique=False)
    op.create_table('compra_venda_biometano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('inicio_producao', sa.String(length=20), nullable=True),
    sa.Column('capacidade_inicial', sa.Float(), nullable=True),
    sa.Column('capacidade_atual', sa.Float(), nullable=True),
    sa.Column('plantas', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('principal_fonte', sa.String(length=200), nullable=True),
    sa.Column('logistica', sa.String(length=200), nullable=True),
    sa.Column('preco', sa.String(length=100), nullable=True),
    sa.Column('valorizacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aplicacao', sa.String(length=200), nullable=True),
    sa.Column('origem_compra', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_venda_biometano_id'), 'compra_venda_biometano', ['id'], unique=False)
    op.create_table('contrapartes_galp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('transportadora', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('uf', sa.String(length=5), nullable=True),
    sa.Column('tipo_consumidor', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrapartes_galp_id'), 'contrapartes_galp', ['id'], unique=False)
    op.create_table('cv_transporte_biometano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('capacidade', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('aplicacao', sa.String(length=200), nullable=True),
    sa.Column('diferencial', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_transporte_biometano_id'), 'cv_transporte_biometano', ['id'], unique=False)
    op.create_table('ecoparques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('tipo_localizacao', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('fonte', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecoparques_id'), 'ecoparques', ['id'], unique=False)
    op.create_table('gasoduto_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectid', sa.Integer(), nullable=True),
    sa.Column('id_duto', sa.Integer(), nullable=True),
    sa.Column('nome_dut_1', sa.String(length=254), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('munic_orig', sa.String(length=254), nullable=True),
    sa.Column('munic_dest', sa.String(length=254), nullable=True),
    sa.Column('comprim_km', sa.Float(), nullable=True),
    sa.Column('shape_stle', sa.Float(), nullable=True),
    sa.Column('diam_pol_x', sa.String(length=50), nullable=True),
    sa.Column('p_max_op', sa.String(length=254), nullable=True),
    sa.Column('transporta', sa.String(length=50), nullable=True),
    sa.Column('fontes', sa.String(length=254), nullable=True),
    sa.Column('fontedata', sa.String(length=50), nullable=True),
    sa.Column('Inic Opera', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_da', sa.Date(), nullable=True),
    sa.Column('last_edi_1', sa.Date(), nullable=True),
    sa.Column('created_us', sa.String(length=254), nullable=True),
    sa.Column('last_edite', sa.String(length=254), nullable=True),
    sa.Column('situacao', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gasoduto_transporte_id'), 'gasoduto_transporte', ['id'], unique=False)
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=True),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('materia_prima', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_id'), 'plant', ['id'], unique=False)
    op.create_table('pontos_entrega_gas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=True),
    sa.Column('transporta', sa.String(length=150), nullable=True),
    sa.Column('classifica', sa.String(length=150), nullable=True),
    sa.Column('fonte', sa.String(length=200), nullable=True),
    sa.Column('segmento', sa.String(length=150), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('id_ponto', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pontos_entrega_gas_id'), 'pontos_entrega_gas', ['id'], unique=False)
    op.create_table('authorized_plant_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('capacidade_nm3_d', sa.Float(), nullable=True),
    sa.Column('empresas', sa.String(length=255), nullable=True),
    sa.Column('link_aea', sa.String(length=500), nullable=True),
    sa.Column('link_ao', sa.String(length=500), nullable=True),
    sa.Column('autorizacao_aea', sa.String(length=100), nullable=True),
    sa.Column('autorizacao_ao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id')
    )
    op.create_table('pending_plant_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('capacidade_de_producao_nm_dia', sa.Float(), nullable=True),
    sa.Column('categoria_materia_prima', sa.String(length=255), nullable=True),
    sa.Column('fonte_1', sa.String(length=255), nullable=True),
    sa.Column('fonte_2', sa.String(length=255), nullable=True),
    sa.Column('investimento', sa.String(length=255), nullable=True),
    sa.Column('previsao_de_conclusao_de_obra', sa.String(length=255), nullable=True),
    sa.Column('tipo_de_autorizacao', sa.String(length=255), nullable=True),
    sa.Column('tipo_localizacao', sa.String(length=255), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_plant_info')
    op.drop_table('authorized_plant_info')
    op.drop_index(op.f('ix_pontos_entrega_gas_id'), table_name='pontos_entrega_gas')
    op.drop_table('pontos_entrega_gas')
    op.drop_index(op.f('ix_plant_id'), table_name='plant')
    op.drop_table('plant')
    op.drop_index(op.f('ix_gasoduto_transporte_id'), table_name='gasoduto_transporte')
    op.drop_table('gasoduto_transporte')
    op.drop_index(op.f('ix_ecoparques_id'), table_name='ecoparques')
    op.drop_table('ecoparques')
    op.drop_index(op.f('ix_cv_transporte_biometano_id'), table_name='cv_transporte_biometano')
    op.drop_table('cv_transporte_biometano')
    op.drop_index(op.f('ix_contrapartes_galp_id'), table_name='contrapartes_galp')
    op.drop_table('contrapartes_galp')
    op.drop_index(op.f('ix_compra_venda_biometano_id'), table_name='compra_venda_biometano')
    op.drop_table('compra_venda_biometano')
    op.drop_index(op.f('ix_cap_num_usinas_acumuladas_id'), table_name='cap_num_usinas_acumuladas')
    op.drop_table('cap_num_usinas_acumuladas')
    op.drop_index(op.f('ix_biometano_dados_abertos_id'), table_name='biometano_dados_abertos')
    op.drop_table('biometano_dados_abertos')
    op.drop_index(op.f('ix_aterros_sanitarios_id'), table_name='aterros_sanitarios')
    op.drop_table('aterros_sanitarios')
    # ### end Alembic commands ###
