"""migration

Revision ID: 22739fa15ad3
Revises: 6a28883356a9
Create Date: 2025-12-16 15:33:15.071534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22739fa15ad3'
down_revision: Union[str, Sequence[str], None] = '6a28883356a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasoduto_transporte', sa.Column('inic_Opera', sa.Integer(), nullable=True))
    op.drop_column('gasoduto_transporte', 'Inic Opera')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasoduto_transporte', sa.Column('Inic Opera', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('gasoduto_transporte', 'inic_Opera')
    # ### end Alembic commands ###
