"""migration

Revision ID: 3c7f1d17bf1c
Revises: 22739fa15ad3
Create Date: 2025-12-17 13:52:36.487618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7f1d17bf1c'
down_revision: Union[str, Sequence[str], None] = '22739fa15ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasoduto_transporte', sa.Column('inic_opera', sa.Integer(), nullable=True))
    op.alter_column('gasoduto_transporte', 'created_da',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('gasoduto_transporte', 'last_edi_1',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('gasoduto_transporte', 'inic_Opera')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasoduto_transporte', sa.Column('inic_Opera', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('gasoduto_transporte', 'last_edi_1',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('gasoduto_transporte', 'created_da',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('gasoduto_transporte', 'inic_opera')
    # ### end Alembic commands ###
