"""migration

Revision ID: 6a28883356a9
Revises: aff604627b28
Create Date: 2025-12-15 15:33:54.723094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a28883356a9'
down_revision: Union[str, Sequence[str], None] = 'aff604627b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasoduto_transporte_coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gasoduto_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gasoduto_id'], ['gasoduto_transporte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gasoduto_id', 'seq', name='uq_gasoduto_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasoduto_transporte_coords')
    # ### end Alembic commands ###
