"""migration

Revision ID: 79bfe6944af4
Revises: 9f9622885385
Create Date: 2026-01-13 11:52:17.235908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bfe6944af4'
down_revision: Union[str, Sequence[str], None] = '9f9622885385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_plant_info', 'concluida',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_plant_info', 'concluida',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
