"""migration

Revision ID: 8852678c36a5
Revises: f364f7333bac
Create Date: 2025-12-18 14:42:14.784124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8852678c36a5'
down_revision: Union[str, Sequence[str], None] = 'f364f7333bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_plant_info', sa.Column('materia_prima', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_plant_info', 'materia_prima')
    # ### end Alembic commands ###
