"""migration

Revision ID: 9ab5bd6b1f34
Revises: ff7bad870e75
Create Date: 2026-01-22 03:24:06.046392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab5bd6b1f34'
down_revision: Union[str, Sequence[str], None] = 'ff7bad870e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biodigestao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_investimento', sa.Float(), nullable=True),
    sa.Column('custo_operacional', sa.Float(), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biodigestao_id'), 'biodigestao', ['id'], unique=False)
    op.create_table('co2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_investimento', sa.Float(), nullable=True),
    sa.Column('custo_operacional', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co2_id'), 'co2', ['id'], unique=False)
    op.create_table('digestato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_investimento', sa.Float(), nullable=True),
    sa.Column('custo_operacional', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digestato_id'), 'digestato', ['id'], unique=False)
    op.create_table('pos_processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_investimento', sa.Float(), nullable=True),
    sa.Column('custo_operacional', sa.Float(), nullable=True),
    sa.Column('estado_biometano', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_processamento_id'), 'pos_processamento', ['id'], unique=False)
    op.create_table('pre_tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_investimento', sa.Float(), nullable=True),
    sa.Column('custo_operacional', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_tratamento_id'), 'pre_tratamento', ['id'], unique=False)
    op.create_table('purificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_investimento', sa.Float(), nullable=True),
    sa.Column('custo_operacional', sa.Float(), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.Column('tecnologia', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purificacao_id'), 'purificacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purificacao_id'), table_name='purificacao')
    op.drop_table('purificacao')
    op.drop_index(op.f('ix_pre_tratamento_id'), table_name='pre_tratamento')
    op.drop_table('pre_tratamento')
    op.drop_index(op.f('ix_pos_processamento_id'), table_name='pos_processamento')
    op.drop_table('pos_processamento')
    op.drop_index(op.f('ix_digestato_id'), table_name='digestato')
    op.drop_table('digestato')
    op.drop_index(op.f('ix_co2_id'), table_name='co2')
    op.drop_table('co2')
    op.drop_index(op.f('ix_biodigestao_id'), table_name='biodigestao')
    op.drop_table('biodigestao')
    # ### end Alembic commands ###
