"""migration

Revision ID: 9f9622885385
Revises: a494bc4d8e25
Create Date: 2026-01-13 11:47:41.845425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9622885385'
down_revision: Union[str, Sequence[str], None] = 'a494bc4d8e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_plant_info', sa.Column('materia_prima_noticias', sa.String(length=255), nullable=True))
    op.drop_column('pending_plant_info', 'empresa_pending')
    op.drop_column('pending_plant_info', 'materia_prima_pending')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_plant_info', sa.Column('materia_prima_pending', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pending_plant_info', sa.Column('empresa_pending', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pending_plant_info', 'materia_prima_noticias')
    # ### end Alembic commands ###
