"""migration

Revision ID: a46b2aa8d69f
Revises: 79bfe6944af4
Create Date: 2026-01-14 12:51:42.592493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46b2aa8d69f'
down_revision: Union[str, Sequence[str], None] = '79bfe6944af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorized_plant_info', sa.Column('empresa', sa.String(length=255), nullable=True))
    op.drop_column('authorized_plant_info', 'empresas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorized_plant_info', sa.Column('empresas', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('authorized_plant_info', 'empresa')
    # ### end Alembic commands ###
