"""migration

Revision ID: a494bc4d8e25
Revises: 8852678c36a5
Create Date: 2025-12-18 14:51:08.301807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a494bc4d8e25'
down_revision: Union[str, Sequence[str], None] = '8852678c36a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_plant_info', sa.Column('materia_prima_pending', sa.String(length=255), nullable=True))
    op.add_column('pending_plant_info', sa.Column('empresa_pending', sa.String(length=255), nullable=True))
    op.drop_column('pending_plant_info', 'materia_prima')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_plant_info', sa.Column('materia_prima', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pending_plant_info', 'empresa_pending')
    op.drop_column('pending_plant_info', 'materia_prima_pending')
    # ### end Alembic commands ###
