"""migration

Revision ID: c57d91d006e6
Revises: a46b2aa8d69f
Create Date: 2026-01-14 13:47:29.498458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57d91d006e6'
down_revision: Union[str, Sequence[str], None] = 'a46b2aa8d69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorized_plant_info', 'empresa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorized_plant_info', sa.Column('empresa', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
