"""migration

Revision ID: d268237e20cc
Revises: 56f851854806
Create Date: 2026-01-26 16:01:15.606354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd268237e20cc'
down_revision: Union[str, Sequence[str], None] = '56f851854806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usinas_alcool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('unidade', sa.String(length=255), nullable=True),
    sa.Column('perfil', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usinas_alcool_id'), 'usinas_alcool', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usinas_alcool_id'), table_name='usinas_alcool')
    op.drop_table('usinas_alcool')
    # ### end Alembic commands ###
