"""migration

Revision ID: f364f7333bac
Revises: fc128bbe7963
Create Date: 2025-12-18 13:53:13.639353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f364f7333bac'
down_revision: Union[str, Sequence[str], None] = 'fc128bbe7963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorized_plant_info', sa.Column('n_da_autorizacao_aea', sa.String(length=100), nullable=True))
    op.add_column('authorized_plant_info', sa.Column('n_da_autorizacao_ao', sa.String(length=100), nullable=True))
    op.drop_column('authorized_plant_info', 'autorizacao_aea')
    op.drop_column('authorized_plant_info', 'autorizacao_ao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorized_plant_info', sa.Column('autorizacao_ao', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('authorized_plant_info', sa.Column('autorizacao_aea', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('authorized_plant_info', 'n_da_autorizacao_ao')
    op.drop_column('authorized_plant_info', 'n_da_autorizacao_aea')
    # ### end Alembic commands ###
