"""migration

Revision ID: ff7bad870e75
Revises: c57d91d006e6
Create Date: 2026-01-22 03:21:13.717173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7bad870e75'
down_revision: Union[str, Sequence[str], None] = 'c57d91d006e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_plant_info', 'materia_prima_noticias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_plant_info', sa.Column('materia_prima_noticias', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
